# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75365b3b9ab78b13e20a49d27d08ec44397a0130474d9b4a630cfa53d1bf5191ac8fde5b71c559439a93429cc3cf4a1ae9b72b5ee58fe00d73a66b843383b57b

test:
  secret_key_base: 7a2d3a0e54e7f0c328eefa1f072b8308bad97d1e7bd2954447715638b4aaf496e1c88c5b926ddf9e89fd7261f0d580d3f1f4991087abdb9ab14436f024768ab7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
